services:
  soa-authentication:
    image: soa-authentication
    ports:
      - "8080:8080"
    environment:
      BIND_ADDRESS: "0.0.0.0:8080"
      DISCORD_CLIENT_ID: "id"
      DISCORD_CLIENT_SECRET: "secret"
      DISCORD_OAUTH2_URI: "http://127.0.0.1:8080/"
      POSTGRES_DSN: "postgres://postgres:postgres@127.0.0.1/postgres"
      REDIRECT_URL: "https://play.storyofalicia.com"

